import React, { useEffect, useRef, useState } from 'react';
import { Box, Typography, Container, Modal, IconButton } from '@mui/material';

const professionalProjectsList = [
  {
    kicker: "PT KAI x Bentley Systems",
    title: "Assetwise Linear Analytics",
    description: "Played a central role in implementing Assetwise Linear Analytics (AWLA) by building custom ETL data-processing scripts. Engineered advanced XML scripting to meticulously parse and ingest raw telemetry files (.PRN / .DATA) generated by the Track Geometry Car (KA Ukur). Successfully integrated these automated ETL pipelines into a robust Java desktop application, enabling the core Bentley software to visualize and analyze vital linear infrastructure data.",
    tags: ['Java', 'XML', 'ETL Pipeline', 'Bentley AWLA', 'Data Parsing'],
    image: "/awla_view.jpeg",
    reverse: false
  },
  {
    kicker: "Executive Monitoring System",
    title: "IRIS Executive Dashboard",
    description: "Architected the backend infrastructure for an executive-level centralized monitoring dashboard. Engineered scalable REST API routes and secure authentication sessions entirely in TypeScript. The platform seamlessly aggregates real-time data streams from diverse IoT monitoring tools—including Gensets, AI CCTV, SSD Early Warning Systems, Flood Detection Sensors, and accelerometers—delivering actionable, high-level insights.",
    tags: ['TypeScript', 'Node.js Backend', 'Authentication', 'REST API', 'IoT Integration'],
    image: "/iris_cms.png",
    reverse: true
  },
  {
    kicker: "Real-Time Telemetry System",
    title: "ROCC Directors Dashboard",
    description: "Engineered Laravel backend for a real-time train performance and live GPS tracking dashboard designed for the Board of Directors. The system aggregates and visualizes high-velocity telemetries for passenger, freight, and official locomotives. Architected an ultra-low latency data pipeline utilizing MQTT topics to broadcast live GPS coordinates and performance metrics flawlessly.",
    tags: ['Laravel', 'PHP', 'MQTT', 'Real-time GPS', 'Backend Architecture'],
    image: "/dashboard.png",
    reverse: false
  },
  {
    kicker: "Fullstack Architecture",
    title: "RAM Enterprise GIS CMS",
    description: "Architected a full-scale GIS Content Management System using Next.js, Node.js, and PostGIS. Orchestrated GeoServer web services and interactive React mapping for advanced spatial analysis. Built a seamless data pipeline connecting a mobile survey app to the database, alongside an AWS S3-powered module that links legal contract documents directly to interactive geographical map polygons.",
    tags: ['Next.js', 'PostGIS', 'GeoServer', 'AWS S3', 'React Leaflet'],
    image: "/RAM-cms.png",
    reverse: true
  },
  {
    kicker: "Spatial Intelligence Client",
    title: "KAI Asset Analytical Dashboard",
    description: "Engineered a highly interactive frontend analytical client acting as the visual extension of the Enterprise GIS CMS. Designed specifically to visualize vast datasets of land and building infrastructures. Developed advanced UI components including a dynamic map layers sidebar for toggling datasets, instantaneous spatial feature extraction, and an intricate bottom insight panel that aggregates critical asset performance metrics and geographical summaries in real-time.",
    tags: ['Frontend Architecture', 'Data Visualization', 'Map UI/UX', 'Spatial Analytics'],
    image: "/dashboard-aset.png",
    reverse: false
  }
];

const ProfessionalProjects: React.FC = () => {
  const [isVisible, setIsVisible] = useState(false);
  const [openImage, setOpenImage] = useState<string | null>(null);
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  return (
    <Box
      component="section"
      id="projects"
      ref={sectionRef}
      sx={{
        pt: { xs: 12, md: 16 },
        pb: { xs: 6, md: 8 },
        bgcolor: 'transparent',
        position: 'relative',
        opacity: isVisible ? 1 : 0,
        transform: isVisible ? 'translateY(0)' : 'translateY(50px)',
        transition: 'all 0.8s ease-out',
      }}
    >
      <Container disableGutters maxWidth={false} sx={{ maxWidth: '1000px', mx: 'auto', px: { xs: 2, md: 4 } }}>
        <Typography
          variant="h2"
          sx={{
            mb: { xs: 8, md: 12 },
            fontWeight: 700,
            fontSize: { xs: '2.2rem', md: '3rem' },
            color: 'white',
            letterSpacing: '-0.02em',
          }}
        >
          Featured Work
        </Typography>

        <Box sx={{ display: 'flex', flexDirection: 'column', gap: { xs: 12, md: 16 } }}>
          {professionalProjectsList.map((project, index) => (
            <Box
              key={index}
              sx={{
                display: 'flex',
                flexDirection: { xs: 'column', md: project.reverse ? 'row-reverse' : 'row' },
                alignItems: 'center',
                gap: { xs: 6, md: 8 },
              }}
            >
              <Box
                sx={{
                  flex: { xs: 'none', md: '0 0 55%' },
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  position: 'relative',
                  perspective: '1200px',
                }}
              >
                <Box
                  sx={{
                    position: 'absolute',
                    top: '50%',
                    left: '50%',
                    transform: 'translate(-50%, -50%)',
                    width: '70%',
                    height: '70%',
                    bgcolor: 'rgba(59, 130, 246, 0.15)',
                    filter: 'blur(60px)',
                    zIndex: 0,
                    borderRadius: '50%',
                  }}
                />
                <Box
                  onClick={() => setOpenImage(project.image)}
                  sx={{
                    width: '100%',
                    maxWidth: '600px',
                    aspectRatio: '16/9',
                    position: 'relative',
                    cursor: 'zoom-in',
                    transform: {
                      xs: 'none',
                      md: project.reverse ? 'rotateY(-10deg) rotateX(4deg) scale(1.02)' : 'rotateY(10deg) rotateX(4deg) scale(1.02)'
                    },
                    transformStyle: 'preserve-3d',
                    boxShadow: {
                      xs: '0 20px 40px rgba(0,0,0,0.4)',
                      md: project.reverse ? '30px 20px 50px rgba(0,0,0,0.6)' : '-30px 20px 50px rgba(0,0,0,0.6)'
                    },
                    borderRadius: '12px',
                    border: '1px solid rgba(255,255,255,0.1)',
                    bgcolor: '#0a0f1c',
                    transition: 'all 0.6s cubic-bezier(0.23, 1, 0.32, 1)',
                    zIndex: 1,
                    overflow: 'hidden',
                    '&:hover': {
                      transform: 'rotateY(0deg) rotateX(0deg) scale(1.08)',
                      boxShadow: '0 30px 60px rgba(0,0,0,0.6)',
                      zIndex: 10,
                    }
                  }}
                >
                  <Box sx={{
                    height: { xs: '20px', md: '28px' },
                    bgcolor: 'rgba(255,255,255,0.04)',
                    borderBottom: '1px solid rgba(255,255,255,0.08)',
                    display: 'flex',
                    alignItems: 'center',
                    px: 2,
                    gap: 1
                  }}>
                    <Box sx={{ width: { xs: 6, md: 10 }, height: { xs: 6, md: 10 }, borderRadius: '50%', bgcolor: '#ef4444', opacity: 0.8 }} />
                    <Box sx={{ width: { xs: 6, md: 10 }, height: { xs: 6, md: 10 }, borderRadius: '50%', bgcolor: '#f59e0b', opacity: 0.8 }} />
                    <Box sx={{ width: { xs: 6, md: 10 }, height: { xs: 6, md: 10 }, borderRadius: '50%', bgcolor: '#10b981', opacity: 0.8 }} />
                  </Box>

                  <Box
                    component="img"
                    src={project.image}
                    alt={project.title}
                    sx={{
                      width: '100%',
                      height: { xs: 'calc(100% - 20px)', md: 'calc(100% - 28px)' },
                      objectFit: 'cover',
                      display: 'block',
                    }}
                  />
                </Box>
              </Box>

              <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <Box sx={{ mb: 3, display: 'flex', alignItems: 'center', gap: 2 }}>
                  <Box
                    sx={{
                      bgcolor: 'rgba(59, 130, 246, 0.15)',
                      color: '#60a5fa',
                      px: 1.5,
                      py: 0.5,
                      borderRadius: '6px',
                      fontSize: '0.75rem',
                      fontWeight: 700,
                      letterSpacing: '0.08em',
                      textTransform: 'uppercase',
                      border: '1px solid rgba(59, 130, 246, 0.3)'
                    }}
                  >
                    {project.kicker}
                  </Box>
                </Box>

                <Typography
                  variant="h3"
                  sx={{
                    fontSize: { xs: '1.8rem', md: '2.2rem' },
                    fontWeight: 700,
                    color: 'white',
                    mb: 2,
                    letterSpacing: '-0.01em',
                  }}
                >
                  {project.title}
                </Typography>

                <Typography
                  sx={{
                    color: 'rgba(255, 255, 255, 0.7)',
                    lineHeight: 1.7,
                    fontSize: '1.05rem',
                    mb: 4,
                  }}
                >
                  {project.description}
                </Typography>

                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1.5 }}>
                  {project.tags.map((tag, tagIndex) => (
                    <Box
                      key={tagIndex}
                      sx={{
                        bgcolor: 'rgba(255, 255, 255, 0.06)',
                        border: '1px solid rgba(255, 255, 255, 0.04)',
                        color: 'rgba(255, 255, 255, 0.9)',
                        px: 2,
                        py: 0.7,
                        borderRadius: '8px',
                        fontSize: '0.85rem',
                        fontWeight: 500,
                      }}
                    >
                      {tag}
                    </Box>
                  ))}
                </Box>
              </Box>
            </Box>
          ))}
        </Box>

        <Typography
          sx={{
            display: 'block',
            textAlign: 'center',
            color: 'rgba(255, 255, 255, 0.4)',
            fontSize: '0.85rem',
            mt: { xs: 10, md: 12 },
            fontStyle: 'italic',
          }}
        >
          * Note: Values and metrics shown in the project screenshots are dummy data for confidentiality and demonstration purposes.
        </Typography>
      </Container>
      <Modal
        open={!!openImage}
        onClose={() => setOpenImage(null)}
        sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          bgcolor: 'rgba(0,0,0,0.85)',
          backdropFilter: 'blur(8px)',
          p: { xs: 2, md: 4 },
          zIndex: 9999,
        }}
      >
        <Box sx={{ position: 'relative', maxWidth: '1200px', width: '100%', outline: 'none' }}>
          <IconButton
            onClick={() => setOpenImage(null)}
            sx={{
              position: 'absolute',
              top: { xs: -40, md: -48 },
              right: 0,
              color: 'white',
              bgcolor: 'rgba(255,255,255,0.1)',
              '&:hover': { bgcolor: 'rgba(255,255,255,0.2)' }
            }}
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </IconButton>
          {openImage && (
            <Box
              component="img"
              src={openImage}
              alt="Fullscreen presentation"
              sx={{
                width: '100%',
                height: 'auto',
                maxHeight: '85vh',
                objectFit: 'contain',
                borderRadius: '8px',
                boxShadow: '0 25px 50px rgba(0,0,0,0.5)',
              }}
            />
          )}
        </Box>
      </Modal>
    </Box>
  );
};

export default ProfessionalProjects;
